name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create .env
        run: |
          echo "VITE_BASE44_APP_ID=${{ secrets.VITE_BASE44_APP_ID }}" >> .env
          echo "VITE_BASE44_FUNCTIONS_VERSION=${{ secrets.VITE_BASE44_FUNCTIONS_VERSION }}" >> .env
          echo "VITE_BASE44_APP_BASE_URL=${{ secrets.VITE_BASE44_APP_BASE_URL }}" >> .env

      - name: Start Application
        run: |
          npm run dev &
          sleep 20

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium Tests
        run: |
          npx mocha tests/*.js --reporter mochawesome

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/